---
- name: Install Apache
  become: true
  apt:
    name: "{{ apache_dependency }}"
- name: Ensure Apache running and start on boot
  become: true
  systemd:
    name: apache2
    state: started
    enabled: true
- name: Active Apache modules
  become: true
  command: "a2enmod {{ item }}"
  with_items: "{{ apache_modules }}"
- name: Create site configuration
  become: true
  template:
    src: ../templates/virtualhost.j2
    dest: "/etc/apache2/sites-available/{{ gitlab_site }}.conf"
- name: Ensure Apache has main server name
  become: true
  lineinfile:
    path: /etc/apache2/apache2.conf
    regexp: "^ServerName"
    line: "ServerName localhost"
- name: Apply site configuration
  become: true
  command: a2ensite {{ gitlab_site }}
- name: Reload Apache
  become: true
  systemd:
    name: apache2
    state: restarted
